sudo: false
cache: bundler
rvm:
  - 2.5.5
gemfile:
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
install:
  - gem install rubocop -v 0.57.2
  - gem install bundler -v 1.17.3
  - bundle --version
  - bundle install
script:
  - bundle exec rake test
  - rubocop
