name: Continuous Integration
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Pkgs
        run: |
          sudo apt-get install libsqlite3-dev
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.5
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Test
        run: bundle exec rake
